services:
  prometheus-write:
    image: prom/prometheus:v3.1.0
    ports:
      - "9090:9090"
    volumes:
      - ./config/writer:/etc/prometheus
      - prometheus-write-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - prometheus

  prometheus-read:
    image: prom/prometheus:v3.1.0
    ports:
      - "9070:9090"
    volumes:
      - ./config/reader:/etc/prometheus
      - prometheus-read-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    networks:
      - prometheus

  grafana:
    image: grafana/grafana:11.4.0
    ports:
      - "3000:3000"
    networks:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

networks:
  prometheus:
    driver: bridge

volumes:
  prometheus-write-data:
  prometheus-read-data:

