services:
  prometheus-write:
    image: prom/prometheus:v3.1.0
    ports:
      - "9090:9090"
    volumes:
      - ./config/writer:/etc/prometheus
      - ./prometheus-write-data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - prometheus
    # 998 é o resultado getent group docker. Grupo docker é o grupo que tem permissão de acessar
    # o /var/run/docker.sock
    user: "1000:998"

  prometheus-read:
    image: prom/prometheus:v3.1.0
    ports:
      - "9070:9090"
    volumes:
      - ./config/reader:/etc/prometheus
      - ./prometheus-read-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    networks:
      - prometheus
    # O 998 é o mesmo motivo de cima, mas estou usando um outro usuário para criação
    user: "1000:998"

  app-metrics:
    build:
      context: app/
    container_name: app-metrics
    ports:
      - "5000:5000"
    networks:
      - prometheus

  grafana:
    image: grafana/grafana:11.4.0
    ports:
      - "3000:3000"
    networks:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus-write
      - prometheus-read

networks:
  prometheus:
    driver: bridge

